name = "MassConversion"
uuid = "2e54bf2d-ba46-4dd2-9ac8-948a8ef92836"
authors = ["Joshua C. Kynaston <josh.c.kynaston@gmail.com>"]
version = "1.0.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
DocumenterTools = "0.1"
PGFPlotsX = "1"
Plots = "1"
StaticArrays = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
